### ISSUE TITLE
console warning on d2d tests async

### ISSUE THREAD

**Issue by twiddlingbits** [twiddlingbits/twr-wasm#32]
Windows 11
Chrome
file:///C:/GitHubClonesDev/twr-wasm/examples/tests-d2d/index.html#async

https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

<img width="614" alt="image" src="https://github.com/user-attachments/assets/640a2faf-b086-4a44-be11-e71bac3c358b">

**Comment by JohnDog3112** [comment]
It seems like the only way to set context attributes (like willReadFrequently) is when first creating the context. So, in order to fix that warning the constructor for twrconcanvas would need to take arguments to pass in when creating the context or the ability to create a new context later.

Example of setting willReadFrequently:
this.ctx = element.getContext("2d", { willReadFrequently: true }) //(compared to [here](https://github.com/twiddlingbits/twr-wasm/blob/2b70c221d0acc02bdcf1faed3cde123e7ddddafd/source/twr-ts/twrconcanvas.ts#L99))

**Comment by twiddlingbits** [comment]
So the warning is being triggered by the way your test app uses the d2d API?  

I am pretty sure GPU acceleration can help a lot with certain 2D operations.  

It sounds like trying to optimize this would require the API user to be able to set it, and that that is not really possible or would require us to change our API a bit for a pretty rare situation.

I suggest we punt, and don't worry about this one.
